name: Create PR base <- develop if master is merged to develop

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  create-pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: List base branches
        id: list_base_branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/base/' | sed 's|origin/||' | tr '\n' ' ')
          echo "branches=${BRANCHES}" >> $GITHUB_ENV

      - name: Create Pull Requests to base branches
        run: |
          for branch in $(echo ${{ env.branches }} | tr ' ' '\n'); do
            TARGET_BRANCH="${branch}"
            PR_TITLE="${TARGET_BRANCH} <- develop"
            PR_BODY="Auto PR ${TARGET_BRANCH} <- develop"
            gh pr create -B "${TARGET_BRANCH}" -H develop --title "${PR_TITLE}" --body "${PR_BODY}" || echo "Failed to create PR for ${TARGET_BRANCH}"
          done
          env:
            GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            branches: ${{ env.branches }}
