name: Create Pull Requests for base/ Branches
run-name: create PRs from develop to base branches

on:
  push:
    branches:
      - develop

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for all branches

      - name: Fetch necessary branches
        run: |
          git fetch origin develop master
          git fetch origin 'refs/heads/base/*:refs/remotes/origin/base/*'

      - name: Get the source branch of the push event
        id: get_source_branch
        run: |
          BEFORE_COMMIT=${{ github.event.before }}
          SOURCE_BRANCH=$(git branch -r --contains $BEFORE_COMMIT | grep -v '\->' | grep -v '/HEAD' | head -n 1 | sed 's|origin/||')
          echo "source_branch=${SOURCE_BRANCH}" >> $GITHUB_ENV

      - name: Check if master is merged into develop
        id: check_merge
        run: |
          if [ "$SOURCE_BRANCH" = "master" ]; then
            if git merge-base --is-ancestor origin/master origin/develop; then
              echo "merge_detected=true" >> $GITHUB_ENV
            else
              echo "merge_detected=false" >> $GITHUB_ENV
            fi
          else
            echo "merge_detected=false" >> $GITHUB_ENV
          fi
        env:
          SOURCE_BRANCH: ${{ env.source_branch }}

      - name: List base/ branches
        id: list_branches
        run: |
          BRANCHES=$(git branch -r | grep 'origin/base/' | sed 's|origin/||' | tr '\n' ' ')
          echo "branches=${BRANCHES}" >> $GITHUB_ENV

      - name: Create Pull Requests
        if: env.merge_detected == 'true'
        run: |
          for branch in $(echo ${{ env.branches }} | tr ' ' '\n'); do
            TARGET_BRANCH="${branch}"
            PR_TITLE="Auto PR: develop to ${TARGET_BRANCH}"
            PR_BODY="This is an automated pull request created from the develop branch to the ${TARGET_BRANCH} branch."
            gh pr create -B "${TARGET_BRANCH}" -H develop --title "${PR_TITLE}" --body "${PR_BODY}" || echo "Failed to create PR for ${TARGET_BRANCH}"
          done
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
          branches: ${{ env.branches }}
          merge_detected: ${{ env.merge_detected }}
