name: Create PR base <- develop if master is merged to develop

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  create-pr:
    # develop <- masterのマージ時のみ起動
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: List base branches
        run: |
          echo "Listing all base branches:"
          git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname:short)' refs/remotes/origin/base/*

      - name: List and filter active base branches
        id: list_and_filter_base_branches
        run: |
          PAST_DATE=$(date -u -d "-3 months" +"%Y-%m-%d")
          echo "Calculated past date: $PAST_DATE"
          ALL_BRANCHES=$(git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname:short)' refs/remotes/origin/base/*)
          echo "All branches:"
          echo "$ALL_BRANCHES"
          BRANCHES=$(echo "$ALL_BRANCHES" | awk -v past_date="$PAST_DATE" '$1 > past_date {print $2}')
          echo "Filtered branches: $BRANCHES"
          echo "branches=${BRANCHES}" >> $GITHUB_ENV

      - name: Create Pull Requests from develop to base branches
        run: |
          for branch in $(echo ${{ env.branches }} | tr ' ' '\n'); do
            TARGET_BRANCH="${branch}"
            PR_TITLE="${TARGET_BRANCH} <- develop"
            PR_BODY="Auto PR ${TARGET_BRANCH} <- develop"
            gh pr create -B "${TARGET_BRANCH}" -H develop --title "${PR_TITLE}" --body "${PR_BODY}" || echo "Failed to create PR for ${TARGET_BRANCH}"
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branches: ${{ env.branches }}
