name: Create PR base <- develop if master is merged to develop

on:
  pull_request:
    types:
      - closed
    branches:
      - develop

jobs:
  create-pr:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' && github.event.pull_request.head.ref == 'master'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all branches

      - name: Print current date
        run: date -u

      - name: Calculate and print past date
        run: |
          PAST_DATE=$(date -u -d "-3 months" +"%Y-%m-%d")
          echo "Past date: $PAST_DATE"
          echo "PAST_DATE=$PAST_DATE" >> $GITHUB_ENV

      - name: List all base branches with commit dates
        run: |
          echo "Listing all base branches with commit dates:"
          git ls-remote --refs origin 'refs/heads/base/*' || echo "No branches found"

      - name: Debug: Check branch dates
        run: |
          echo "Checking each branch's date against the past date $PAST_DATE:"
          git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname:short)' 'refs/remotes/origin/base/*' | while read -r date branch; do
            echo "Branch $branch with commit date $date"
            if [[ "$date" > "$PAST_DATE" ]]; then
              echo "Branch $branch is active (committed on $date)"
            else
              echo "Branch $branch is not active (committed on $date)"
            fi
          done

      - name: List active base branches
        id: list_active_base_branches
        run: |
          echo "Filtering branches updated after $PAST_DATE:"
          BRANCHES=$(git for-each-ref --sort=-committerdate --format='%(committerdate:short) %(refname:short)' 'refs/remotes/origin/base/*' | while read -r date branch; do
            if [[ "$date" > "$PAST_DATE" ]]; then
              echo "${branch#refs/remotes/origin/}"
            fi
          done | tr '\n' ' ')
          echo "Filtered branches: $BRANCHES"
          echo "branches=$(echo $BRANCHES | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Print branches from environment variable
        run: |
          echo "Branches: ${{ env.branches }}"

      - name: Create Pull Requests from develop to base branches
        run: |
          for branch in ${{ env.branches }}; do
            TARGET_BRANCH="${branch}"
            PR_TITLE="${TARGET_BRANCH} <- develop"
            PR_BODY="Auto PR ${TARGET_BRANCH} <- develop"
            gh pr create -B "${TARGET_BRANCH}" -H develop --title "${PR_TITLE}" --body "${PR_BODY}" || echo "Failed to create PR for ${TARGET_BRANCH}"
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
